# Generated by Django 5.0 on 2024-02-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.BooleanField(default=0),
        ),
    ]
